# 파이썬 기반의 AI를 위한 기초수학, 확률및통계

In [1]:
## 강봉주 
## bonjour.kang@gmail.com
##
## 파이썬
##

## 기본 데이터 형

In [2]:
# int
x = 100
type(x)

int

In [3]:
# float
x = 0.0
type(x)

float

In [4]:
# bool
x = True
type(x)

bool

In [5]:
# str
x = 'hello!\nWelcome to ML world'
type(x)

str

In [6]:
# bytes
x = b'bong'
type(x)

bytes

## 컨테이너 데이터 형

In [7]:
# list
x = [1,2,3]
type(x)

list

In [8]:
# 리스트와 각 원소의 데이터 형
x = ["a",2.3,3, b"bong"]
print(type(x))
print(type(x[0]))
print(type(x[1]))
print(type(x[2]))
print(type(x[3]))

<class 'list'>
<class 'str'>
<class 'float'>
<class 'int'>
<class 'bytes'>


In [9]:
# tuple
x = (1,2,3)
type(x)

tuple

In [10]:
# dict
x = {"key1": 100, "key2": 200}
type(x)

dict

In [11]:
x = dict(key1=100, key2=200)
type(x)

dict

In [12]:
# set
x = {"key1", "key2"}
type(x)

set

In [13]:
x = {1, 2, 3, 3}
x

{1, 2, 3}

## 값의 할당

In [14]:
# 기본 할당
x = 1 + 1.2
x

2.2

In [15]:
# 같은 값 할당
x = y = 0
[x, y]

[0, 0]

In [16]:
# 각각 해당 값 할당
x, y = 1, 0.9
[x, y]

[1, 0.9]

In [17]:
# 값 바꾸기
x, y = y, x
[x, y]

[0.9, 1]

In [18]:
# 값 증가
x = 0
x += 2
x

2

In [19]:
# 값 감소
x = 0
x -= 3 
x

-3

In [20]:
# 정의는 되었지만 값 없음
x = None
[x, type(x)]

[None, NoneType]

In [116]:
# 변수 제거
# del x
# x

NameError: name 'x' is not defined

## 형 변환

In [22]:
# 문자열에서 정수로
[int("100"), ord('\n')]

[100, 10]

In [23]:
# 16진법으로 표시된 문자열을 정수로
int("ff", base=16)

255

In [24]:
# 실수를 정수로
[int(2.1), round(13.2)]

[2, 13]

In [25]:
# 정수를 실수로
float(0)

0.0

In [26]:
# 정수, 실수를 문자로
[str(100), str(100.0)]

['100', '100.0']

In [27]:
# 정수를 문자로
chr(97)

'a'

In [28]:
# 리스트를 바이트로
bytes([97,98,99,100])

b'abcd'

In [29]:
# 문자열을 리스트로
list("abc")

['a', 'b', 'c']

In [30]:
# 리스트를 사전으로
dict([(1, "abc"), (2, "cde")])

{1: 'abc', 2: 'cde'}

In [31]:
# 문자열을 집합으로
set("abcde")

{'a', 'b', 'c', 'd', 'e'}

In [32]:
# 리스트를 문자열로
x = "-".join(['bong', 'ju', 'kang'])
x

'bong-ju-kang'

In [33]:
# 문자열을 리스트로
x.split("-")

['bong', 'ju', 'kang']

In [34]:
# NoneType을  bool로
bool(None)

False

In [35]:
# 0 논리값
bool(0)

False

In [36]:
# 1 논리값
bool(1)

True

In [37]:
# False 논리값
bool(False)

False

In [38]:
# True 논리값
bool(True)

True

In [39]:
# 널 문자열 논리값
bool("")

False

## 순서열(sequence) 컨테이너 인덱싱

In [40]:
# 순서열(sequence)을 갖는 컨테이너 정의
x = [2, 4, 6, 8, 10]
len(x)

5

In [41]:
# 해당 위치 값 가져오기
[x[0], x[4]]

[2, 10]

In [117]:
# 인덱스 오류: 해당 위치가 인덱스의 범위에 벗어남
# x[5]

NameError: name 'x' is not defined

In [43]:
# 음수 인덱스
[x[-1], x[-len(x)]]

[10, 2]

In [44]:
# 조각내기
x[1:2]

[4]

In [45]:
x[::]

[2, 4, 6, 8, 10]

In [46]:
x[:]

[2, 4, 6, 8, 10]

In [47]:
# 3 보다 작은 인덱스 값까지
x[:3]

[2, 4, 6]

In [48]:
# 처음부터 마지막 직전까지
x[:-1]

[2, 4, 6, 8]

In [49]:
# 인덱스가 2씩 증가하며 처음부터 끝까지 
x[::2]

[2, 6, 10]

In [50]:
# 인덱스가 -2씩 증가하며 끝에서 처음까지
x[::-2]

[10, 6, 2]

In [51]:
# 순서열 원소 제거: 처음부터 인덱스가 2보다 작은 값까지
x = [2, 4, 6, 8, 10]
del x[:2]
x

[6, 8, 10]

## 논리 연산자

In [52]:
# > 연산자
0 > 1

False

In [53]:
# == 연산자
0 == 1

False

In [54]:
# != 연산자
0 != 1

True

In [55]:
# and, & 연산자
(0 > 1) & (1 > 0)

False

In [56]:
# or, | 연산자
(0 > 1) | (1 > 0)

True

In [57]:
# not 연산자
not (0 > 1)

True

## 문(statement) 구성

In [58]:
if (0 == 0):
    print((0 == 0))
    if not (0 > 1):
        print (not (0 > 1))
print((0 > 1) and (0 > 1))

True
True
False


## 패키지 가져오기(import)

In [59]:
# 모듈 탐색을 위한 경로 확인
import sys
sys.path

['C:\\Users\\banene02\\OneDrive\\KMU\\project\\winter2020\\source\\book',
 'C:\\ProgramData\\Anaconda3\\python37.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\banene02\\.ipython']

In [60]:
# numpy 패키지의 가져오기, 그리고 별명으로 np를 사용
import numpy as np 
np.__version__

'1.17.4'

In [61]:
# 파이썬 경로의 matplotlib 디렉토리 밑의 pyplot 파일을 지칭
import matplotlib.pyplot as plt
plt

<module 'matplotlib.pyplot' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\matplotlib\\pyplot.py'>

## 조건문

In [62]:
# 조건문 구조
income = 100
if income < 100:
    grade = "low"
elif income < 200:
    grade = "middle"
else:
    grade = "high"

grade

'middle'

## 수학 연산과 함수

In [63]:
# // 연산자
[3 // 2, -3 // -2, 3 // -2]

[1, 1, -2]

In [64]:
# 필요한 패키지 가져오기
import numpy as np

# 행렬 곱: @
x = np.array([[1,2], [3,4]])
y = np.array([[0,1], [1,0]])
x @ y

array([[2, 1],
       [4, 3]])

In [65]:
# 원소별 곱
x * y

array([[0, 2],
       [3, 0]])

In [66]:
# 수학 함수
# 싸인 함수
np.sin(np.pi/2)

1.0

In [67]:
# 자연 로그
np.log([1, np.e, np.e**2, 0])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([  0.,   1.,   2., -inf])

In [68]:
# 천장 함수
np.ceil(9.9)

10.0

## 조건 반복문

In [69]:
# while 반복문

# index 값이 11이면 while 반복 문을 탈출 따라서 합은 index=10 까지만의 합임
value = 0
index = 1
while index <= 10:
    value += index**2
    index += 1
    
[value, index]

[385, 11]

In [70]:
# for 반복문

name = "bong ju kang"
for index, value in enumerate(name):
    if value == 'g':
        print("index number=", index)

index number= 3
index number= 11


In [71]:
# range 함수를 이용한 for 반복문

name = "bong ju kang"
[name[index] for index in range(len(name))]

['b', 'o', 'n', 'g', ' ', 'j', 'u', ' ', 'k', 'a', 'n', 'g']

## 컨테이너형 일반 연산

In [72]:
# 일반 연산: len, min, max, sorted
name = "bong ju kang"
value = "123456789"

[len(name), len(value), min(value),max(name), sorted(name) ]

[12, 9, '1', 'u', [' ', ' ', 'a', 'b', 'g', 'g', 'j', 'k', 'n', 'n', 'o', 'u']]

In [73]:
# 일반 연산: enumerate
[{a:b} for a, b in enumerate(name)]

[{0: 'b'},
 {1: 'o'},
 {2: 'n'},
 {3: 'g'},
 {4: ' '},
 {5: 'j'},
 {6: 'u'},
 {7: ' '},
 {8: 'k'},
 {9: 'a'},
 {10: 'n'},
 {11: 'g'}]

In [74]:
# 일반 연산: zip
# 같은 위치에 있는 값을 반환하는 반복자
[val for val in zip(('a', 'b', 'c'), ('c', 'b', 'd', 'e'))] 

[('a', 'c'), ('b', 'b'), ('c', 'd')]

In [75]:
[val for val in zip(name, value)]

[('b', '1'),
 ('o', '2'),
 ('n', '3'),
 ('g', '4'),
 (' ', '5'),
 ('j', '6'),
 ('u', '7'),
 (' ', '8'),
 ('k', '9')]

In [76]:
# 일반 연산자: index(위치), count(건수)
[name.index('k'), name.count('g')]

[8, 2]

In [77]:
# 일반 연산자: 값 in
x ='b'
x in name

True

## 리스트 연산

In [78]:
# 리스트 생성
value =[]
value

[]

In [79]:
# 리스트 원소 추가:
value.append('b')
value.append('a')
value.append('n')
value.append('e')
value.append('n')
value.append('e')
value

['b', 'a', 'n', 'e', 'n', 'e']

In [80]:
# 리스트 원소 제거: remove
value.remove('b') 
value

['a', 'n', 'e', 'n', 'e']

In [81]:
# 리스트에 순서열(sequence) 추가: extend
value.extend('bnn')
value

['a', 'n', 'e', 'n', 'e', 'b', 'n', 'n']

In [82]:
# 리스트 마지막 값 제거: pop
value.pop()
value

['a', 'n', 'e', 'n', 'e', 'b', 'n']

In [83]:
# 리스트 원소 위치 값 제거: pop
value.pop(-1)
value

['a', 'n', 'e', 'n', 'e', 'b']

In [84]:
# 리스트 정렬: sort, reverse
value.sort()
value

['a', 'b', 'e', 'e', 'n', 'n']

## 딕셔너리 연산

In [85]:
# 딕셔너리 생성
score = {'lang':80, 'math':90, 'his':75}
score

{'lang': 80, 'math': 90, 'his': 75}

In [86]:
# 딕셔너리 키 조회
score.keys()

dict_keys(['lang', 'math', 'his'])

In [87]:
# 딕셔너리 값 조회: 키 순서대로
score.values()

dict_values([80, 90, 75])

In [88]:
# 딕셔너리 값 조회: 키와 get
[score['lang'], score.get('lang')]

[80, 80]

In [89]:
# 딕셔너리 값 수정: 키와 update
score['math']=100
score.update({'math':100})
score

{'lang': 80, 'math': 100, 'his': 75}

In [90]:
# 딕셔너리 특정 키 제거
del score['lang']
score

{'math': 100, 'his': 75}

In [91]:
# 딕셔너리 초기화
score.clear()
score

{}

## 집합 연산

In [92]:
# 집합 정의
A = {'a', 'b', 'c'}
B = {'b', 'c', 'd', 'e'}
[A, B]

[{'a', 'b', 'c'}, {'b', 'c', 'd', 'e'}]

In [93]:
# 합집합
A | B

{'a', 'b', 'c', 'd', 'e'}

In [94]:
# 교집합
A & B

{'b', 'c'}

In [95]:
# 차집합
A - B

{'a'}

In [96]:
# 집합 비교: <, >, ==
C = A | B
[A < C, A < B, B < C, A == B]

[True, False, True, False]

In [97]:
# 원소 추가
A.add('d')
A

{'a', 'b', 'c', 'd'}

In [98]:
# 집합 추가
A.update({1, 2, 3})
A

{1, 2, 3, 'a', 'b', 'c', 'd'}

In [99]:
# 원소 제거
A.remove('d')
A

{1, 2, 3, 'a', 'b', 'c'}

In [100]:
# 집합 복사
D = A.copy()
D

{1, 2, 3, 'a', 'b', 'c'}

## 함수 정의

In [101]:
# 함수 정의 예

def bnn_add(x,y):
    """
    이 함수는 피 연산자를 받아서 덧셈을 처리해준다.
    :param x: 덧셈이 가능한 값
    :param y: 덧셈이 가능한 값
    :return: 덧셈 후 결과 값을 반환
    """
    return x + y

In [102]:
# 함수 활용
import numpy as np
bnn_add(np.array([1,9]), np.array([2.0, 3]))

array([ 3., 12.])

## 문자열 연산

In [103]:
# 문자열 생성
name='\n    bong ju kang'
name

'\n    bong ju kang'

In [104]:
# 문자열 앞뒤 화이트 스페이스(white space) 제거:strip

# 화이트스페이스의 종류
# chr(9) # 수평 탭(tab), '\t'
# chr(10) # 라인피드(line feed), '\n'
# chr(11) # 수직 탭, '\x0b'
# chr(12) # 폼피드(form feed), '\x0c'
# chr(13) # 캐리지리턴(carriage return), '\r'
# chr(32) # 공백(space), ' '

name.strip()

'bong ju kang'

In [105]:
# 문자열의 시작하는 인덱스: index
name.index('k')

13

In [106]:
# 대소문자 변환: lower, upper
['KANG'.lower(), 'banene'.upper()]

['kang', 'BANENE']

In [107]:
# 대소문자 서로 변환: swapcase
'Kang, Bong Ju'.swapcase()

'kANG, bONG jU'

In [108]:
# 숫자, 문자로만 구성된 문자열인지 확인; isalnum()
'Bonjour Kang 2020!'.isalnum()

False

In [109]:
# 문자열 분리: split
'Kang, Bonjour'.split(',')

['Kang', ' Bonjour']

In [110]:
# 문자열 결합
','.join(['Kang', 'Bong Ju'])

'Kang,Bong Ju'

## 포맷 구성하기

In [111]:
# 소숫점 이하 2째 자리까지
"${:.2f}".format(12345.12345) 

'$12345.12'

In [112]:
# 콤마 포맷
"{:,}원".format(1234567890) 

'1,234,567,890원'

In [113]:
# 콤마 포맷과 소숫점 이하 1째 자리까지
"{:,.1f}원".format(12345.77) 

'12,345.8원'

In [114]:
# 포맷할 값의 2번째 인자에 대한 포맷 지정: 오른쪽 정렬까지 지정(>)
"{1:>20s}".format(12345, 'bong ju kang')

'        bong ju kang'

In [115]:
# 포맷할 값의 2번째 인자에 대한 포맷 지정: 가운데 정렬까지 지정(^)
"{1:^20s}".format(12345, 'bong ju kang') 

'    bong ju kang    '