# 파이썬 기반의 AI를 위한 기초수학, 확률및통계

In [1]:
## 강봉주 
## bonjour.kang@gmail.com
##
## 벡터와 행렬
##

In [2]:
# 필요한 패키지
import numpy as np
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

# 버전 확인
print(np.__version__)
# 1.17.4
print(scipy.__version__)
# 1.3.2

1.17.4
1.3.2


# 벡터 표현

In [3]:
# 벡터의 생성
v = np.array([0.61, 0.93, 0.24, 0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [4]:
# 벡터의 원소
v = np.array([0.61, 0.93, 0.24, 0.27])
v[0]

0.61

In [5]:
# 벡터의 크기
v = np.array([0.61, 0.93, 0.24, 0.27])
v.shape

(4,)

In [6]:
# 부분 벡터의 생성
v = np.array([0.61, 0.93, 0.24, 0.27])
v_sub = v[0:2]
v_sub

array([0.61, 0.93])

## 특별한 벡터

In [7]:
# 영 벡터
size = 3
zeros = np.zeros(shape=(size,))
zeros

array([0., 0., 0.])

In [8]:
# 단위 벡터
size = 3
e = np.zeros(shape=(3,))

# 단위 벡터의 위치
i = 1

# 단위 벡터 생성
e[i]=1
e

array([0., 1., 0.])

In [9]:
# 1 벡터
size = 3
one = np.ones(shape=(size, ))
one

array([1., 1., 1.])

## 벡터의 연산

In [10]:
# 벡터의 덧셈
a = np.array([1, 3])
b = np.array([3, 1])
a + b

array([4, 4])

In [11]:
# 교환 법칙
a + b == b + a

array([ True,  True])

In [12]:
# 결합 법칙
d = np.array([1, 2])
(a + b) + d == a + (b + d)

array([ True,  True])

In [13]:
# 벡터의 뺄셈
a = np.array([3, 1])
b = np.array([1, 3])
b-a

array([-2,  2])

In [14]:
# 스칼라-벡터 곱
alpha = 1/2
a = np.array([2, 3])
alpha * a

array([1. , 1.5])

In [15]:
# 교환 법칙
alpha * a == a * alpha

array([ True,  True])

In [16]:
# 분배 법칙
beta = 0.7
(alpha + beta) * a == alpha * a +beta * a

array([ True,  True])

## 내적

In [17]:
# 내적 계산
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

# 원소별 곱 벡터
a * b

array([-1, -4, 12])

In [18]:
# 원소별 곱 벡터 합
np.sum(a*b)

7

In [19]:
# 함수 이용
np.inner(a, b)

7

In [20]:
np.dot(a, b)

7

In [21]:
# 내적의 성질
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

# 교환 법칙
np.dot(a, b) == np.dot(b, a)

True

In [22]:
# 결합 법칙
alpha= 0.5
np.dot(alpha * a, b) == alpha * np.dot(a, b)

True

In [23]:
# 분배 법칙
c = np.array([1, 2, 3])
np.dot(a+b, c) == np.dot(a,c) + np.dot(b, c)

True

In [24]:
# 내적의 활용
a = np.array([1, 2, 3])
size = len(a)
ones = np.ones(shape=(size,))

# 합의 표현
np.dot(ones, a)

6.0

In [25]:
# 평균의 표현
np.dot(ones, a) / len(a)

2.0

In [26]:
# 제곱합의 표현
np.dot(a, a)

14

## 벡터 노름

In [27]:
# 필요한 패키지
from scipy import linalg as la

# 벡터 노름의 계산
a = np.array([2, 3])
la.norm(a).round(3)

3.606

In [28]:
# 벡터 노름의 성질
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

# 스칼라 곱
beta = 0.5
la.norm(beta * a) == np.abs(beta) * la.norm(a)

True

In [29]:
# 삼각형의 한 변의 길이는 다른 두변의 길이의 합보다 작다
la.norm(a + b) <= la.norm(a) + la.norm(b)

True

In [30]:
# 길이는 0보다 크거나 작다
la.norm(a) >= 0

True

### 정규직교 벡터

In [31]:
# 정규직교 벡터 확인
a1 =np.array([0, 0, 1]).reshape(-1, 1)
a2 = 1/np.sqrt(2) * np.array([1, 1, 0]).reshape(-1, 1)
a3 = 1/np.sqrt(2) * np.array([1, -1, 0]).reshape(-1, 1)

# 노름=1, 열들의 곱=0
A = np.concatenate((a1, a2, a3), axis=1)
np.round(A.T @ A, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

# 행렬

## 행렬 표현

In [32]:
# 정의: 2차원 배열
A = np.array(np.random.RandomState(123).normal(size=16)).reshape(4, 4)
A.round(3)

array([[-1.086,  0.997,  0.283, -1.506],
       [-0.579,  1.651, -2.427, -0.429],
       [ 1.266, -0.867, -0.679, -0.095],
       [ 1.491, -0.639, -0.444, -0.434]])

In [33]:
# 행렬의 크기
A = np.random.RandomState(123).randint(1, 12, size=12).reshape(3, 4)
A.shape

(3, 4)

In [34]:
# 행벡터와 열벡터
A = np.random.RandomState(123).randint(1, 12, size=12).reshape(3, 4)
A

array([[ 3,  3,  7,  2],
       [ 4, 11, 10,  7],
       [ 2,  1,  2, 10]])

In [35]:
# 열 벡터
A[:,0]

array([3, 4, 2])

In [36]:
# 행 벡터
A[0,:]

array([3, 3, 7, 2])

In [37]:
# 행렬의 표기법
A[0, 0]

3

In [38]:
A[1, 3]

7

## 행렬 연산

In [39]:
# 행렬 덧셈
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(3, 9).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
B

array([[3, 4, 5],
       [6, 7, 8]])

In [41]:
A + B

array([[ 4,  6,  8],
       [10, 12, 14]])

In [42]:
# 행렬 덧셈의 성질
# 교환 법칙
A + B == B + A

array([[ True,  True,  True],
       [ True,  True,  True]])

In [43]:
# 결합 법칙
C = np.arange(5, 11).reshape(2, 3)
(A+B)+C == A+(B+C)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [44]:
# 스칼라와 행렬 곱: *
c = 0.1
c*A

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [45]:
# 스칼라와 행렬 곱 성질
c*A == A*c

array([[ True,  True,  True],
       [ True,  True,  True]])

In [46]:
# 행렬의 전치
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
# 행렬 전치의 성질
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(3, 9).reshape(2, 3)

A.T + B.T == (A + B).T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [48]:
c = 0.1
(c*A).T == c*A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [49]:
# 행렬 곱
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
# 행렬곱 연산자: @
A @ B

array([[22, 28],
       [49, 64]])

In [52]:
# 행렬곱 함수
np.matmul(A, B)

array([[22, 28],
       [49, 64]])

In [53]:
# 행렬곱의 성질
# AB !=  BA
A = np.arange(1, 5).reshape(2, 2)
A

array([[1, 2],
       [3, 4]])

In [54]:
B = np.arange(5, 9).reshape(2, 2)
B

array([[5, 6],
       [7, 8]])

In [55]:
A @ B

array([[19, 22],
       [43, 50]])

In [56]:
B @ A

array([[23, 34],
       [31, 46]])

In [57]:
# 행렬 곱의 전치
(A @ B).T

array([[19, 43],
       [22, 50]])

In [58]:
B.T @ A.T

array([[19, 43],
       [22, 50]])

In [59]:
# 부분 행렬
A = np.arange(1, 13).reshape(4, 3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
# 유형 1
A[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [61]:
# 유형 2
A[:, 1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [62]:
# 유형 3
A[[0, 2], :][:, [1, 2]]

array([[2, 3],
       [8, 9]])

## 특별한 행렬

In [63]:
#  영 행렬
size = 3
np.zeros(shape=(size, size))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
# 항등 행렬
np.identity(n=size)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# 대각 행렬
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [66]:
# 상삼각 행렬
np.triu([[1,2,3],[1, 2, 7],[7,8,5]], k=0)

array([[1, 2, 3],
       [0, 2, 7],
       [0, 0, 5]])

In [67]:
# 직교 행렬(orthogonal matrix)
A = np.array([[1,0], [0, -1]])
A

array([[ 1,  0],
       [ 0, -1]])

In [68]:
A.T @ A

array([[1, 0],
       [0, 1]])

In [69]:
A @ A.T

array([[1, 0],
       [0, 1]])

## QR분해

In [70]:
# 선형 방정식과 후방 대입법
A = np.array([[1, 1], [1/2, -1]])
XTX = A.T@A
XTX

array([[1.25, 0.5 ],
       [0.5 , 2.  ]])

In [71]:
# QR 분해
Q, R = la.qr(XTX)
R.round(2)

array([[-1.35, -1.21],
       [ 0.  ,  1.67]])

In [72]:
b = np.array([4, 2])
np.round(Q.T @ b, 2) 

array([-4.46,  0.37])

In [73]:
# 하우스홀더 변환 이해
A = np.array([[5, 1, 5], 
        [3, 9 , 8], 
        [2, 1, 4]])
A

array([[5, 1, 5],
       [3, 9, 8],
       [2, 1, 4]])

In [74]:
# 첫번째 열 벡터 추출
a = A[:,0].reshape(-1, 1)
a

array([[5],
       [3],
       [2]])

In [75]:
# 하우스홀더 행렬 Q1 구성
size = A.shape[0]
e1 = np.identity(n=size)[:,0].reshape(-1, 1)
# u, v 벡터 구성
u = a - la.norm(a)*e1
u

array([[-1.164414],
       [ 3.      ],
       [ 2.      ]])

In [76]:
v = u / la.norm(u)
v

array([[-0.30732141],
       [ 0.79178387],
       [ 0.52785591]])

In [77]:
Q1 = np.identity(n=size) - 2 * v @ v.T
np.round(Q1, 2)

array([[ 0.81,  0.49,  0.32],
       [ 0.49, -0.25, -0.84],
       [ 0.32, -0.84,  0.44]])

In [78]:
# 하우스-홀더 변환과 변환 후의 결과
np.round(Q1 @ A, 2)

array([[ 6.16,  5.52,  9.25],
       [-0.  , -2.63, -2.94],
       [-0.  , -6.76, -3.29]])

In [79]:
Q, R = la.qr(A)
np.round(Q, 3)

array([[-0.811,  0.479, -0.336],
       [-0.487, -0.871, -0.067],
       [-0.324,  0.109,  0.94 ]])

In [80]:
np.round(R, 3)

array([[-6.164, -5.516, -9.247],
       [ 0.   , -7.251, -4.137],
       [ 0.   ,  0.   ,  1.544]])

In [81]:
# 행렬 정의
A = np.array([[1, -1, -1, 1], 
              [2, -1, 1, -1],
              [4, 1, -1, 1],
              [2, 1, -1, -1]
             ])
A

array([[ 1, -1, -1,  1],
       [ 2, -1,  1, -1],
       [ 4,  1, -1,  1],
       [ 2,  1, -1, -1]])

In [82]:
# Q, R 행렬 구하기
Q, R = la.qr(A)
Q.round(3)

array([[-0.2  , -0.587,  0.784,  0.   ],
       [-0.4  , -0.65 , -0.588,  0.267],
       [-0.8  ,  0.273,  0.   , -0.535],
       [-0.4  ,  0.398,  0.196,  0.802]])

In [83]:
R.round(3)

array([[-5.   , -0.6  ,  1.   , -0.2  ],
       [ 0.   ,  1.908, -0.734, -0.063],
       [ 0.   ,  0.   , -1.569,  1.177],
       [ 0.   ,  0.   ,  0.   , -1.604]])

## 역행렬

In [84]:
# 좌 역행렬(left inverse)
A = np.array([[-3, -4],
             [4, 6],
             [1, 1]])
A

array([[-3, -4],
       [ 4,  6],
       [ 1,  1]])

In [85]:
B = 1/9 * np.array([[-11, -10, 16],
                   [7, 8, -11]])
np.round(B@A, 3)

array([[ 1., -0.],
       [ 0.,  1.]])

In [86]:
C = 1/2 * np.array([[0, -1, 6],
                   [0, 1, -4]])
np.round(C@A, 3)

array([[1., 0.],
       [0., 1.]])

In [87]:
# 선형 방정식의 해: over-determined
b = np.array([1, -2, 0])
np.round(A@(B@b))

array([ 1., -2.,  0.])

In [88]:
np.round(A@(C@b))

array([ 1., -2.,  0.])

In [89]:
# 역행렬의 몇 가지 성질 확인
A = np.array([[7, 6, 7],
       [3, 5, 3],
       [7, 2, 4]])
A

array([[7, 6, 7],
       [3, 5, 3],
       [7, 2, 4]])

In [90]:
# 행렬 계수 구하기
np.linalg.matrix_rank(A)

3

In [91]:
# 역행렬 구하기
A_inverse = la.inv(A)
np.round(A_inverse, 2)

array([[-0.27,  0.2 ,  0.33],
       [-0.18,  0.41,  0.  ],
       [ 0.57, -0.55, -0.33]])

In [92]:
# 역행렬의 역행렬
la.inv(A_inverse)

array([[7., 6., 7.],
       [3., 5., 3.],
       [7., 2., 4.]])

In [93]:
# 스칼라 곱 역행렬
c = 0.1
np.round(la.inv(c*A), 2)

array([[-2.75,  1.96,  3.33],
       [-1.76,  4.12, -0.  ],
       [ 5.69, -5.49, -3.33]])

In [94]:
np.round(1/c * la.inv(A), 2)

array([[-2.75,  1.96,  3.33],
       [-1.76,  4.12,  0.  ],
       [ 5.69, -5.49, -3.33]])

In [95]:
# 전치와 역행렬
np.round(la.inv(A.T), 2)

array([[-0.27, -0.18,  0.57],
       [ 0.2 ,  0.41, -0.55],
       [ 0.33,  0.  , -0.33]])

In [96]:
np.round(la.inv(A).T, 2)

array([[-0.27, -0.18,  0.57],
       [ 0.2 ,  0.41, -0.55],
       [ 0.33,  0.  , -0.33]])

In [97]:
# 곱의 역행렬
B = np.array([[8, 4, 7],
       [6, 5, 5],
       [1, 2, 8]])
B

array([[8, 4, 7],
       [6, 5, 5],
       [1, 2, 8]])

In [98]:
np.round(la.inv(A @ B), 2)

array([[-0.12,  0.06,  0.13],
       [ 0.02,  0.12, -0.13],
       [ 0.08, -0.11, -0.03]])

In [99]:
np.round(la.inv(B) @ la.inv(A), 2)

array([[-0.12,  0.06,  0.13],
       [ 0.02,  0.12, -0.13],
       [ 0.08, -0.11, -0.03]])

In [100]:
# 직교 행렬의 역행렬
Q, _ = la.qr(A)
np.round(Q.T, 2)

array([[-0.68, -0.29, -0.68],
       [-0.32, -0.71,  0.63],
       [-0.66,  0.64,  0.39]])

In [101]:
np.round(la.inv(Q), 2)

array([[-0.68, -0.29, -0.68],
       [-0.32, -0.71,  0.63],
       [-0.66,  0.64,  0.39]])

In [102]:
# 행렬 정의
A = np.array([[1, -1, -1, 1], 
              [2, -1, 1, -1],
              [4, 1, -1, 1],
              [2, 1, -1, -1]
             ])
b = np.array([-1, 6, 0, 2]).reshape(-1, 1)

In [103]:
# Q, R 행렬 구하기
Q, R = la.qr(A)

# 해 구하기
x = la.inv(R) @ Q.T @ b
x.round(3)

array([[ 1.],
       [-1.],
       [ 1.],
       [-2.]])

In [104]:
# 의사 역행렬
A = np.array([[-3, 4], 
             [4, 6],
             [1,1]])
A

array([[-3,  4],
       [ 4,  6],
       [ 1,  1]])

In [105]:
# 열 독립여부 확인
np.linalg.matrix_rank(A)

2

In [106]:
# 의사 역행렬 계산
pinv = la.inv(A.T@A)@A.T
pinv.round(3)

array([[-0.175,  0.111,  0.033],
       [ 0.118,  0.086,  0.011]])

In [107]:
# 함수 값으로 확인
la.pinv(A).round(3)

array([[-0.175,  0.111,  0.033],
       [ 0.118,  0.086,  0.011]])

In [108]:
# 좌 역행렬 확인
np.round(pinv@A, 3)

array([[ 1., -0.],
       [-0.,  1.]])

## 행렬식

In [109]:
import sympy
a11, a12, a13, a21, a22, a23, a31, a32, a33 = sympy.symbols('a11, a12, a13, a21, a22, a23, a31, a32, a33')

A = sympy.Matrix([[a11, a12, a13],
                      [a21, a22, a23],
                      [a31, a32, a33]])
A

Matrix([
[a11, a12, a13],
[a21, a22, a23],
[a31, a32, a33]])

In [110]:
sympy.det(A)

a11*a22*a33 - a11*a23*a32 - a12*a21*a33 + a12*a23*a31 + a13*a21*a32 - a13*a22*a31

In [111]:
# 예제
A = np.array([[-2, 2, -3],
               [-1, 1, 3],
               [2, 0, -1]])
la.det(A)

18.0

## 고유값과 고유벡터

In [112]:
# 고유값과 고유벡터의 계산
A = np.array([[2, 1],
              [1, 2]])
w, v = la.eig(A)

In [113]:
# 고유값: 복소수 표현식
w

array([3.+0.j, 1.+0.j])

In [114]:
# 각 열이 해당 고유값에 대응되는 고유벡터
# 값은 정규화(normalized)되어 있음
v.round(3)

array([[ 0.707, -0.707],
       [ 0.707,  0.707]])

In [115]:
# 행렬 정의
A = np.array([[ 9, -5,  1],
       [-5,  5, -3],
       [ 1, -3, 19]])
A

array([[ 9, -5,  1],
       [-5,  5, -3],
       [ 1, -3, 19]])

In [116]:
# 고유값 벡터
w, _ = la.eig(A)
w.round(3)

array([ 1.398+0.j, 11.577+0.j, 20.026+0.j])

In [117]:
# 대각합(trace)
np.diag(A).sum()

33

In [118]:
# 고유값 합
np.sum(w).round(3).real

33.0

In [119]:
# 행렬식
la.det(A)

324.0

In [120]:
# 고유값 곱
np.prod(w).round(3).real

324.0